name: Build and Deploy MyQuranPlan

on:
  push:
    branches: ["main", "master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil Kode
        uses: actions/checkout@v4
      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: 3. Install Dependensi
        run: npm install
      - name: 4. Build Project
        run: npm run build
      - name: 5. Simpan Hasil Build
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Folder hasil kompilasi Vite

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 6. Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4