-- Hapus tabel jika sudah ada (opsional, hati-hati jika ada data penting)
-- DROP TABLE IF EXISTS settings, app_users, students;

-- 1. TABEL SETTINGS
CREATE TABLE settings (
  id integer PRIMARY KEY DEFAULT 1,
  guruhalaqohdata jsonb DEFAULT '{}'::jsonb,
  kelaslist jsonb DEFAULT '[]'::jsonb,
  institutionname text DEFAULT 'Nama Sekolah Anda',
  institutionlogo text,
  targetreguler text DEFAULT '2 Juz',
  targetalquran text DEFAULT ''
);

-- 2. TABEL APP_USERS
CREATE TABLE app_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text UNIQUE NOT NULL,
  name text NOT NULL,
  password text NOT NULL,
  role text DEFAULT 'guru',
  status text DEFAULT 'pending',
  resetRequested boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. TABEL STUDENTS
CREATE TABLE students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  kelas text,
  halaqoh text,
  initial text,
  photo text,
  records jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- BUCKET UNTUK FOTO SISWA (Hanya bisa dibuat via SQL jika punya permission, disarankan buat via UI)
-- insert into storage.buckets (id, name, public) values ('student_photos', 'student_photos', true) on conflict (id) do nothing;

-- KEBIJAKAN KEAMANAN (Row Level Security)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for anon settings" ON settings FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for anon app_users" ON app_users FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for anon students" ON students FOR ALL USING (true) WITH CHECK (true);

-- ENABLE REALTIME UNTUK STUDENTS (Penting untuk MainApp.jsx baris 128)
-- Aktifkan Realtime di dashboard Supabase (Database -> Replication -> Source -> Centang `students`)
-- Atau dengan SQL (jika replication sudah ada):
begin;
  -- remove the supabase_realtime publication
  drop publication if exists supabase_realtime;

  -- re-create the supabase_realtime publication with no tables
  create publication supabase_realtime;
commit;

alter publication supabase_realtime add table students;
